### ISSUE TITLE
ExpressJS auto updater

### ISSUE THREAD

**Issue by calebeaires** [JohnMunsch/selfhelp#1]
I came to selfhelp looking for an solution to auto update an express/angular app. Reading the docs I have found some way to do so, but I have wonder if you have an suggestion on how to create an auto-updater to express.js node app on a server like [Express Auto Updater](https://github.com/electron-userland/electron-builder/tree/master/packages/electron-updater) do. Something that do this.

1. download zip from location;
2. Unzip;
3. npm install updates packages
4. stop current project
5. start the new project using pm2

**Comment by JohnMunsch** [comment]
I have not found anything exactly like that. But for my original interests, I believe that Electron (https://electron.atom.io/) is absolutely the best possible solution.

It embeds Node.js together with a browser to create a complete UI for applications (think something like Slack or Atom) and has provisions for automatic upgrades. Perhaps that would work for your needs as well.

**Comment by calebeaires** [comment]
My solution (http://gaio.io) will be installed on a ubuntu server by users. I intend to publish it on AWS Marktplace, so when I public at github an new version, the app will update itself. I have found solution like this: https://github.com/petrkrulis/grunt-node-auto-deploy and
